#1. DISPARADOR

trigger:
- master

#2. AGENTE
pool:
  vmImage: 'windows-latest'

#3. VARIABLES
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

#4. ADMINISTRADOR DE PAQUETES
stages:
- stage: Build
  jobs:
  - job: Build
    #pool:
      #vmImage: 'ubuntu-latest'
    steps:
    - task: NuGetToolInstaller@1
      displayName: 'Instalar Nuget en agente'
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
      displayName: 'Restaurar dependencias con Nuget'