trigger:
- master

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: echo "hello to my first Build!!!"

- stage: dev_deploy
  jobs:
  - deployment: dev_deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: 'dev-hello'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "hello, dev world!!!!"