#1. DISPARADOR

trigger:
- master

#2. AGENTE
pool:
  vmImage: 'windows-latest'

#3. VARIABLES
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

#4. ADMINISTRADOR DE PAQUETES
steps:
- task: NuGetToolInstaller@1