#1. DISPARADOR

trigger:
- master

#2. AGENTE
pool:
  vmImage: 'windows-latest'

#3. VARIABLES
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

stages:
- stage: Paquetes
  jobs:
  - job: Paquetes
    #pool:
      #vmImage: 'ubuntu-latest'
    steps:
    #4. ADMINISTRADOR DE PAQUETES
    - task: NuGetToolInstaller@1
      displayName: 'Instalar Nuget en agente'
    #5. RESTAURO DEPENDENCIAS PROPIAS
    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'
      displayName: 'Restaurar dependencias con Nuget'

- stage: Build
  jobs:
  - job: Build
    #pool:
      #vmImage: 'ubuntu-latest'
    steps:
    #5. CONSTRUCCIÓN O BUILD
    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'