trigger:
- master

stages:
- stage: BuildStage
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-latest'
      steps:
      - script: echo "Hola build!!!"

- stage: QaStage
  jobs:
  - deployment: qa_deploy
    pool:
      vmImage: 'mac-latest'
    environment: 'qa'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Hola Qa"

- stage: ProductionStage
  jobs:
  - deployment: production_deploy
    pool:
      vmImage: 'windows-latest'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo "Hola Producción"
